BaseSource.WebApp/Areas/Admin/Controllers/AccountMoonAtaController.cs
using BaseSource.ApiIntegration.AdminApi;
using BaseSource.ViewModels.Admin;
using BaseSource.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaseSource.WebApp.Areas.Admin.Controllers
{
    public class AccountMoonAtaController : BaseAdminController
    {
        private readonly IAccountMoonAtaApiAdminClient _accountMoonAtaApiAdminClient;
        public AccountMoonAtaController(IAccountMoonAtaApiAdminClient accountMoonAtaApiAdminClient)
        {
            _accountMoonAtaApiAdminClient = accountMoonAtaApiAdminClient;
        }
        public async Task<IActionResult> Index(string username, string email, int? page = 1)
        {
            var request = new GetAccountMoonAtaPagingRequest_Admin()
            {
                Page = page.Value,
                PageSize = 10,
                UserName = username,
                Email = email
            };

            var result = await _accountMoonAtaApiAdminClient.GetPagings(request);
            if (!result.IsSuccessed)
            {
                return NotFound();
            }

            return View(result.ResultObj);
        }
        public ActionResult Create()
        {
            return PartialView("_CreateAcc");
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateAccountMoonAtaVm model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new ApiErrorResult<string>(ModelState.GetListErrors()));
            }
            var result = await _accountMoonAtaApiAdminClient.Create(model);
            if (!result.IsSuccessed)
            {
                ModelState.AddListErrors(result.ValidationErrors);
                return Json(new ApiErrorResult<string>(ModelState.GetListErrors()));
            }
            return Json(new ApiSuccessResult<string>());
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var result = await _accountMoonAtaApiAdminClient.Delete(id);
            if (result.IsSuccessed)
            {
                return Json(new ApiSuccessResult<string>());
            }
            return Json(new ApiErrorResult<string>(result.Message));
        }
    }
}

BaseSource.WebApp/Areas/Admin/Controllers/DocumentMoonAtaController.cs
using BaseSource.ApiIntegration.AdminApi;
using BaseSource.ViewModels.Admin;
using BaseSource.ViewModels.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace BaseSource.WebApp.Areas.Admin.Controllers
{
    public class DocumentMoonAtaController : BaseAdminController
    {
        private readonly IDocumentMoonAtaApiAdminClient _apiClient;
        public DocumentMoonAtaController(IDocumentMoonAtaApiAdminClient apiClient)
        {
            _apiClient = apiClient;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var result = await _apiClient.GetAlls();
            if (!result.IsSuccessed)
            {
                return NotFound();
            }
            var model = new CreateDocumentMoonAtaVm();
            if (result.ResultObj != null)
            {
                model.FileName = result.ResultObj.FileName;
                model.FileUrl = result.ResultObj.FileUrl;
                model.UrlVideo = result.ResultObj.UrlVideo;
            }
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CreateDocumentMoonAtaVm model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new ApiErrorResult<string>(ModelState.GetListErrors()));
            }
            var result = await _apiClient.Create(model);
            if (!result.IsSuccessed)
            {
                return Json(new ApiErrorResult<string>(result.ValidationErrors));
            }

            return Json(new ApiSuccessResult<string>(Url.Action("Index")));
        }
    
    }
}

BaseSource.WebApp/Areas/Admin/Controllers/MoonAtaCandleHistoryController.cs
using BaseSource.ApiIntegration.AdminApi;
using BaseSource.ViewModels.Admin;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BaseSource.WebApp.Areas.Admin.Controllers
{
    public class MoonAtaCandleHistoryController : BaseAdminController
    {
        private readonly IMoonAtaCandleHistoryApiAdminClient _moonAtaCandleHistoryApiAdminClient;
        public MoonAtaCandleHistoryController(IMoonAtaCandleHistoryApiAdminClient moonAtaCandleHistoryApiAdminClient)
        {
            _moonAtaCandleHistoryApiAdminClient = moonAtaCandleHistoryApiAdminClient;
        }

        public IActionResult Index()
        {
            var model = new GetAccountMoonAtaRequestVm()
            {
                StartDate = DateTime.Now,
                EndDate = DateTime.Now
            };
            return View(model);
        }
        public async Task<IActionResult> ExportFile(GetAccountMoonAtaRequestVm model)
        {
            string fileName = DateTime.Now.ToString("ddMMyyyy_HHmmss") + "_MoonAtaCandleHistory.txt";
            var lstData = await _moonAtaCandleHistoryApiAdminClient.GetAlls(model);
            string temp = "";
            if (lstData.ResultObj.Count > 0)
            {
                foreach (var item in lstData.ResultObj)
                {
                    temp += item.IsGreen ? "B" : "S";
                }

            }
            byte[] bin = Encoding.ASCII.GetBytes(temp);
            return File(bin, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

BaseSource.WebApp/Areas/Admin/Controllers/UserController.cs
using BaseSource.ApiIntegration.AdminApi;
using BaseSource.Shared.Enums;
using BaseSource.ViewModels.Admin;
using BaseSource.ViewModels.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaseSource.WebApp.Areas.Admin.Controllers
{
    public class UserController : BaseAdminController
    {
        private readonly IUserAdminApiClient _apiClient;
        public UserController(IUserAdminApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public async Task<IActionResult> Index(string username, string email, int? page = 1)
        {
            var request = new GetUserPagingRequest_Admin()
            {
                Page = page.Value,
                PageSize = 20,
                UserName = username,
                Email = email
            };

            var result = await _apiClient.GetPagings(request);
            if (!result.IsSuccessed)
            {
                return NotFound();
            }

            return View(result.ResultObj);
        }


        public async Task<ActionResult> EditUserRole(string id)
        {
            var result = await _apiClient.GetUserRoles(id);
            if (!result.IsSuccessed)
            {
                return NotFound();
            }

            return PartialView("_EditUserRole", result.ResultObj);
        }

        [HttpPost]
        public async Task<ActionResult> EditUserRole(RoleAssignVm model)
        {
            if (!ModelState.IsValid)
            {
                return Json(false);
            }

            var result = await _apiClient.RoleAssign(model);
            if (!result.IsSuccessed)
            {
                return Json(false);
            }

            return Json(true);
        }
        public ActionResult CreateUser()
        {
            return PartialView("_CreateUser");
        }
        [HttpPost]
        public async Task<ActionResult> CreateUser(CreateUserVm model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new ApiErrorResult<string>(ModelState.GetListErrors()));
            }
            var result = await _apiClient.CreateUser(model);
            if (!result.IsSuccessed)
            {
                ModelState.AddListErrors(result.ValidationErrors);
                return Json(new ApiErrorResult<string>(ModelState.GetListErrors()));
            }
            return Json(new ApiSuccessResult<string>());
        }
        [HttpPost]
        public async Task<ActionResult> ResetPassword(string userId)
        {
            var result = await _apiClient.ResetPassword(userId);
            if (!result.IsSuccessed)
            {
                ModelState.AddListErrors(result.ValidationErrors);
                return Json(new ApiErrorResult<string>(ModelState.GetListErrors()));
            }
            return Json(new ApiSuccessResult<string>());
        }
        [HttpPost]
        public async Task<ActionResult> DeleteUser(string userId)
        {
            var result = await _apiClient.DeleteUser(userId);
            if (result.IsSuccessed)
            {
                return Json(new ApiSuccessResult<string>());
            }
            return Json(new ApiErrorResult<string>(result.Message));
        }
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordAdminVm model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await _apiClient.ChangePassword(model);
            if (result.IsSuccessed)
            {
                string url = Url.Action("Login", "Account", new { Area = "" });
                return Redirect(url);
            }
            ModelState.AddListErrors(result.ValidationErrors);
            return View(model);
        }

    }
}

BaseSource.WebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Admin</title>
    <link href="~/admin/css/styles.css" rel="stylesheet" />
    <link href="~/admin/libs/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />

    <link href="~/admin/css/site.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body class="nav-fixed" id="page-top">
    <nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" id="sidenavAccordion">
        @await Html.PartialAsync("_NavTopbar")
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            @await Html.PartialAsync("_SideBar")
        </div>
        <div id="layoutSidenav_content">
            <main class="container-fluid py-4">
                @RenderBody()
            </main>
            <footer class="footer mt-auto footer-light">
                <div class="container-fluid">
                    <div class="text-center">
                        <div>© Copyright @DateTime.Now.Year by <a href="/">Kteam.</a> All Rights Reserved.</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/admin/libs/feather/feather.min.js"></script>
    <script src="~/admin/js/scripts.js"></script>
    <script src="~/admin/libs/ckeditor/ckeditor.js"></script>

    <script src="~/lib/toastr/toastr.min.js"></script>

    <script src="~/admin/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BaseSource.WebApp/Areas/Admin/Views/Shared/_NavTopBar.cshtml
<!-- Navbar Brand-->
<!-- * * Tip * * You can use text or an image for your navbar brand.-->
<!-- * * * * * * When using an image, we recommend the SVG format.-->
<!-- * * * * * * Dimensions: Maximum height: 32px, maximum width: 240px-->
<a class="navbar-brand" href="@Url.Action("Index", "Home")">
    BOWEB
</a>
<!-- Sidenav Toggle Button-->
<button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 mr-lg-2" id="sidebarToggle"><i data-feather="menu"></i></button>

<ul class="navbar-nav align-items-center ml-auto">
    @await Component.InvokeAsync("UserInfoTopBar")
</ul>

BaseSource.WebApp/Areas/Admin/Views/Shared/_Pager.cshtml
@model PagedResultBase

@{
    var urlTemplate = Model.PageUrl + "?page={0}";
    urlTemplate = ViewContext.HttpContext.Request.Query.ConvertToUrlString(urlTemplate, new[] { "page", "pageSize" });

    var startIndex = Math.Max(Model.PageNumber - 2, 1);
    var finishIndex = Math.Min(Model.PageNumber + 2, Model.PageCount);


    //var pageSize = ViewContext.HttpContext.Request.Query["pageSize"] == "20" ? 20 : 10;

    var urlTemplateFull = urlTemplate;// + $"&pageSize={pageSize}";
}

<div class="rows-page d-flex justify-content-between align-items-center ">
    <div class="list-current d-flex align-items-center">
        @*<span>Rows per page: </span>
        <select class="pageSize-select" onchange="this.value == '' ? void (0) : window.location.href = this.value;">
            @if (Model.PageSize == 10)
            {
                <option value="@string.Format(urlTemplate + "&pageSize=10", 1)" selected>10</option>
                <option value="@string.Format(urlTemplate + "&pageSize=20", 1)">20</option>
                
            }
            else
            {
                <option value="@string.Format(urlTemplate + "&pageSize=10", 1)">10</option>
                <option value="@string.Format(urlTemplate + "&pageSize=20", 1)" selected>20</option>
               
            }
        </select>*@
    </div>
    <nav class="rows-page__navigation align-items-center">
        @if (Model.PageCount > 1)
        {
            <ul class="pagination">
                @if (Model.PageNumber != startIndex)
                {
                    <li class="page-item">
                        <a class="page-link text-secondary" href="@urlTemplateFull.Replace("{0}", "1")">&#10094;&#10094;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link text-secondary" href="@urlTemplateFull.Replace("{0}", (Model.PageNumber-1).ToString())">&#10094;</a>
                    </li>
                }
                @for (var i = startIndex; i <= finishIndex; i++)
                {
                    if (i == Model.PageNumber)
                    {
                        <li class="page-item active">
                            <span class="page-link">@i <span class="sr-only">(current)</span></span>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link text-secondary" href="@urlTemplateFull.Replace("{0}", i.ToString())">@i</a>
                        </li>
                    }
                }
                @if (Model.PageNumber != finishIndex)
                {
                    <li class="page-item">
                        <a class="page-link text-secondary" href="@urlTemplateFull.Replace("{0}", (Model.PageNumber+1).ToString())">&#10095;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link text-secondary" href="@urlTemplateFull.Replace("{0}", Model.PageCount.ToString())">&#10095;&#10095;</a>
                    </li>
                }
            </ul>
        }
    </nav>
</div>

BaseSource.WebApp/Areas/Admin/Views/Shared/_SideBar.cshtml
<nav class="sidenav shadow-right sidenav-dark">
    <div class="sidenav-menu">
        <div class="nav accordion" id="accordionSidenav">
            <a class="nav-link user-nav" href="@Url.Action("Index", "User")">
                <div class="nav-link-icon"><i data-feather="users"></i></div>
                User
            </a>
            <a class="nav-link acc-nav" href="@Url.Action("Index", "AccountMoonAta")">
                <div class="nav-link-icon"><i data-feather="file-text"></i></div>
                Acc MoonAta
            </a>
            <a class="nav-link history-nav" href="@Url.Action("Index", "MoonAtaCandleHistory")">
                <div class="nav-link-icon"><i data-feather="file-text"></i></div>
                MoonAtaCandleHistory
            </a>
            @if (User.IsInRole(SystemConstants.Roles.Admin))
            {
                <a class="nav-link document-nav" href="@Url.Action("Index", "DocumentMoonAta")">
                    <div class="nav-link-icon"><i data-feather="file-text"></i></div>
                    Tài Liệu
                </a>
            }

        </div>
    </div>
</nav>